SELECT * FROM customer LIMIT 22

-- What is the total revenue generated by male vs female customers?
select gender,sum(purchase_amount) as total_revenue 
from customer 
group by gender;


-- Which customers used a discount but still spent more than the average purchase amount?
select customer_id, purchase_amount
from customer
where discount_applied = 'Yes' and purchase_amount >= (select avg(purchase_amount) from customer)


-- Which are the top 5 products with the highest average review rating?
select item_purchased, round(avg(review_rating::numeric),2)  as "Avg highest rating" from customer 
group by item_purchased
order by avg(review_rating) desc 
limit 5;


-- Compare the average purchase amount between standard and express shipping.
select shipping_type, round(avg(purchase_amount),2) from customer
where shipping_type in ('Standard', 'Express')
group by shipping_type;


-- Do subscribed customers spend more? (Compare average spend and total revenue between subscribers and non-subscribers.)
select subscription_status,
count(customer_id) as "total customers",
round(avg(purchase_amount),2) as "Avg spend", 
round(sum(purchase_amount),2) as "total revenue"
from customer
group by subscription_status;


-- Which 5 products have the highest percentage of purchases with discounts applied?
select item_purchased,  
round(100 * sum(case when discount_applied='Yes' then 1 else 0 end)/count(*),2) as discount_rate
from customer
group by item_purchased
order by discount_rate desc
limit 5;


-- Segment customers into new, returning, and loyal based on previous purchases,
--and show the count of each segment.
with customer_type as (
select previous_purchases,
case 
	 when previous_purchases = 1 then 'New'
	 when previous_purchases between 2 and 10 then 'Returning'
	 else 'Loyal'
	 end as customers_segment
from customer
) 

select customers_segment, count(*) as "Number of Customers"
from customer_type
group by customers_segment


-- What are the top three most purchased products within each category?
with item_count as(
select item_purchased,
	category as each_category,
	count(customer_id) as total_orders, --Used to find total orders in each category 
	ROW_NUMBER() OVER(partition by category order by count(customer_id)desc) as item_rank
from customer	
group by category,item_purchased
)
select each_category,item_purchased,item_rank,total_orders
from item_count
where item_rank<=3 


-- Are customers with more than five previous purchases (repeat buyers) also likely to subscribe?
select subscription_status,
count(customer_id) as repeated_customers
from customer
where previous_purchases > 5
group by subscription_status


-- What is the revenue contribution by each age group?
select age_group,sum(purchase_amount) as revenue_contribution from customer
group by age_group
order by revenue_contribution desc
